name: marker
description: GitHub Action for installing and running Marker linting
branding:
  icon: edit-3
  color: white

inputs:
  install-only:
    description: >
      If set to `true` then the action will only install `cargo marker`,
      and will skip running `cargo marker check`. Use this if you want to run
      something more complex than just `cargo marker check`. If you think there
      may be a frequent use case for running a different command then we will be
      glad if you open a feature request for that to extend the action input
      parameters.

    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - run: ${GITHUB_ACTION_PATH:?}/scripts/release/install.${{ runner.os == 'Windows' && 'ps1' || 'sh' }}
      shell: bash

    - run: cargo marker check
      if: ${{ inputs.install-only == 'false' }}
      shell: bash
