[workspace]
changelog_update = false

[[package]]
changelog_path   = "CHANGELOG.md"
changelog_update = true
name             = "marker_api"

changelog_include = [
  "marker_utils",
  "marker_uitest",
  "marker_error",
  "marker_rustc_driver",
  "cargo-marker",
]
