name: release
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description:
          (Optional) Version to set for the release. If not specified, the latest
          numbered version found in the changelog will be used.
      dev-version:
        required: false
        description:
          (Optional) Version to set for the next development cycle. If not specified,
          then the `version` with the incremented minor will be used.

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - id: version
        run: >
          echo "version=${{
              github.event.inputs.version || '$(scripts/release/get-version-from-changelog.sh)'
          }}"
          >> "$GITHUB_OUTPUT"
      - id: dev-version
        run: >
          echo "dev-version=${{
              github.event.inputs.dev-version || '$(scripts/release/get-next-dev-version.sh)'
          }}"
          >> "$GITHUB_OUTPUT"

      # Create a release commit and tag
      - run: scripts/release/set-version.sh ${{ steps.version.outputs.version }}
      - run: git commit -am "Release v${{ steps.version.outputs.version }}"
      - run: git tag v${{ steps.get-version.outputs.version }}"

      # Craete a next dev version commit
      - run: scripts/release/set-version.sh ${{ steps.dev-version.outputs.dev-version }}
      - run: git commit -am "Development v${{ steps.dev-version.outputs.dev-version }}"

      # Push the commits and tags
      - run: git push --atomic --follow-tags
